# local_llm.py
import os
from pathlib import Path
from llama_cpp import Llama
from typing import Generator

# -----------------------
# Singleton LLM instance
# -----------------------
_llm_instance = None

def get_llm_instance() -> Llama:
    """
    Returns a singleton Llama instance to avoid reloading the model multiple times.
    """
    global _llm_instance
    if _llm_instance is None:
        model_path = os.getenv("LLM_MODEL")
        if not model_path or not Path(model_path).exists():
            raise FileNotFoundError(f"LLM model not found at {model_path}")

        _llm_instance = Llama(
            model_path=model_path,
            n_ctx=4096,       # max context length
            n_threads=4,      # adjust based on CPU
            n_gpu_layers=20   # 0 if no GPU/Metal
        )
    return _llm_instance

# -----------------------
# Streaming generator
# -----------------------
def stream_llm(prompt: str, max_tokens: int = 2048, temperature: float = 0.7, top_p: float = 0.9) -> Generator[str, None, None]:
    """
    Generator function to yield tokens as they are generated by the model.
    Use this for streaming responses.
    """
    llm = get_llm_instance()

    for output in llm(
        prompt,
        stream=True,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
    ):
        text = output["choices"][0]["text"]
        if text:
            yield text

# -----------------------
# Non-streaming generation
# -----------------------
def generate_llm(prompt: str, max_tokens: int = 2048, temperature: float = 0.7, top_p: float = 0.9) -> str:
    """
    Generate full text in one call (non-streaming).
    Useful for debugging or when streaming is not needed.
    """
    llm = get_llm_instance()

    output = llm(
        prompt,
        stream=False,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
    )

    full_text = output["choices"][0]["text"]
    return full_text.strip()